### ISSUE TITLE
What is "pusage"?

### ISSUE THREAD

**Issue by rucksman** [datenschuft/SMA-EM#60]
There in an undocumented value in the MQTT output of the energy meter called "pusage". At least it is not mentioned in config.sample. What is it and what is it's unit? Thanks for this wonderful tool!

**Comment by datenschuft** [comment]
pusage is calulated with pvdata. so you have to enable pvdata_kostal_json.py or pvdata.py to get data from your inverter.
pusage = pvpower + pconsume - psupply (calculated in influxdb.py and/or mqtt.py)
pusage = energy from your photovoltaik + consuming energy (SMA-EM) - energy you supply (SMA-EM)
Pusage is the power you currently use (in your house) and it's units are Watt (W)

pusage is not documentated in mqtt.py because it depends on the feature pvdata. (could gone better)

**Comment by rucksman** [comment]
Thanks for the explanation!
